### ISSUE TITLE
SVG Fallback

### ISSUE THREAD

**Issue by RanolP** [RanolP/oAuth-Buttons#2]
현재 oAuth-Buttons는 로고에 svg를 사용하므로 IE 같이 svg를 지원하지 않는 브라우저에 대응할 수 없음. 따라서 png 파일을 생성하고 svg를 불러올 수 없을 시 png를 렌더링하는 방식으로 작동해야함.

**Comment by dalbodeule** [comment]
아이콘에 궂이 색상이 없어도 되는 관계로 웹폰트를 이용하여 처리하는 것으로 결정함.

다만 grunt 에서 웹폰트를 생성할 수 있는 모듈들은 css를 처리하기에 무리가 있어보여 수작업으로 처리하기로 결정함.

**Comment by dalbodeule** [comment]
웹폰트 생성 및 사용에 무리가 있는 관계로 svg/png를 사용하는 것으로 결정, modernizr를 사용하여 svg 등 일부 기술 미지원 브라우저에 대응하는 방향으로 제작
