### ISSUE TITLE
네이버 로그인 아이콘 SVG

### ISSUE THREAD

**Issue by ryush00** [RanolP/oAuth-Buttons#3]
https://developers.naver.com/docs/login/bi/

공식 SVG가 있습니다.

**Comment by dalbodeule** [comment]
현재 공식 SVG가 적용되어있는 것으로 확인되어있으며, 추후 [oAuth-Buttons/logo-providers](https://github.com/oAuth-Buttons/logo-providers)로 통합될 예정이므로 만약 적용이 되어있지 아니하다 하여도 그때 수정하도록 하겠습니다.
